import theFileShouldExportAFunction from "tests/theFileShouldExportAFunction";
import useOnRenderBackgroundCallback from "hooks/useOnRenderBackgroundCallback";

theFileShouldExportAFunction(useOnRenderBackgroundCallback);
