import theFileShouldExportAFunction from "tests/theFileShouldExportAFunction";
import useOnRenderForegroundCallback from "hooks/useOnRenderForegroundCallback";

theFileShouldExportAFunction(useOnRenderForegroundCallback);
