import renderSolidColorBackground from "functions/renderSolidColorBackground";
import theFileShouldExportAFunction from "tests/theFileShouldExportAFunction";

theFileShouldExportAFunction(renderSolidColorBackground);
